package com.medisupplyg4.ui.theme

import androidx.compose.ui.graphics.Color

// Colores Material3 del tema MediSupply
val md_theme_primary = Color(0xFF636117)
val md_theme_onPrimary = Color(0xFFFFFFFF)
val md_theme_primaryContainer = Color(0xFFEAE78E)
val md_theme_onPrimaryContainer = Color(0xFF4A4900)
val md_theme_secondary = Color(0xFF616042)
val md_theme_onSecondary = Color(0xFFFFFFFF)
val md_theme_secondaryContainer = Color(0xFFE7E4BF)
val md_theme_onSecondaryContainer = Color(0xFF49482D)
val md_theme_tertiary = Color(0xFF3E6656)
val md_theme_onTertiary = Color(0xFFFFFFFF)
val md_theme_tertiaryContainer = Color(0xFFC0ECD7)
val md_theme_onTertiaryContainer = Color(0xFF264E3F)
val md_theme_error = Color(0xFFBA1A1A)
val md_theme_onError = Color(0xFFFFFFFF)
val md_theme_errorContainer = Color(0xFFFFDAD6)
val md_theme_onErrorContainer = Color(0xFF93000A)
val md_theme_background = Color(0xFFFDF9EC)
val md_theme_onBackground = Color(0xFF1C1C14)
val md_theme_surface = Color(0xFFFDF9EC)
val md_theme_onSurface = Color(0xFF1C1C14)
val md_theme_surfaceVariant = Color(0xFFE6E3D1)
val md_theme_onSurfaceVariant = Color(0xFF48473A)
val md_theme_outline = Color(0xFF797869)
val md_theme_outlineVariant = Color(0xFFCAC7B6)
val md_theme_scrim = Color(0xFF000000)
val md_theme_inverseSurface = Color(0xFF323128)
val md_theme_inverseOnSurface = Color(0xFFF5F1E3)
val md_theme_inversePrimary = Color(0xFFCDCA75)
val md_theme_primaryFixed = Color(0xFFEAE78E)
val md_theme_onPrimaryFixed = Color(0xFF1D1D00)
val md_theme_primaryFixedDim = Color(0xFFCDCA75)
val md_theme_onPrimaryFixedVariant = Color(0xFF4A4900)
val md_theme_secondaryFixed = Color(0xFFE7E4BF)
val md_theme_onSecondaryFixed = Color(0xFF1D1C06)
val md_theme_secondaryFixedDim = Color(0xFFCBC8A4)
val md_theme_onSecondaryFixedVariant = Color(0xFF49482D)
val md_theme_tertiaryFixed = Color(0xFFC0ECD7)
val md_theme_onTertiaryFixed = Color(0xFF002116)
val md_theme_tertiaryFixedDim = Color(0xFFA4D0BC)
val md_theme_onTertiaryFixedVariant = Color(0xFF264E3F)
val md_theme_surfaceDim = Color(0xFFDEDACD)
val md_theme_surfaceBright = Color(0xFFFDF9EC)
val md_theme_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_surfaceContainerLow = Color(0xFFF7F4E6)
val md_theme_surfaceContainer = Color(0xFFF2EEE0)
val md_theme_surfaceContainerHigh = Color(0xFFECE8DB)
val md_theme_surfaceContainerHighest = Color(0xFFE6E2D5)